import pandas as pd
df=pd.read_csv('stud.csv')
print(df)
df.set_index('rollno',inplace=True)
print(df[['name','mark']])
print(df[['name','mark']].sort_values(by='name'))
print(df[['name','mark']].sort_values(by='mark',ascending=False))
print(df['mark'].mean())
print(df['mark'].median())
print(df['mark'].mode())
print(df['mark'].min())
print(df['mark'].max())
print(df['mark'].var())
print(df['mark'].std())
import matplotlib.pyplot as plt
df['mark'].hist()
plt.show()
df.drop('place',axis=1,inplace=True)
print(df)
